export const emoji = {
  smile: "😊",
  laugh: "😂",
  thumbsUp: "👍",
  clap: "👏",
  heart: "❤️",
  star: "⭐",
  fire: "🔥",
  speaker: "🔊",
  watch: "👀",
  check: "✅",
  checkMark: "✔️",
  checkMarkBox: "☑️",
  cross: "❌",
  warning: "⚠️",
  info: "ℹ️",
  question: "❓",
}
