export const colour = {
  reset: "\x1b[0m",
  bright: "\x1b[1m",
  dim: "\x1b[2m",
  underscore: "\x1b[4m",
  blink: "\x1b[5m",
  reverse: "\x1b[7m",
  hidden: "\x1b[8m",
  italic: "\x1b[3m",

  black: "\x1b[30m",
  red: "\x1b[31m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  grey: "\x1b[90m",
  magenta: "\x1b[35m",
  cyan: "\x1b[36m",
  white: "\x1b[37m",

  bgBlack: "\x1b[40m",
  bgRed: "\x1b[41m",
  bgGreen: "\x1b[42m",
  bgYellow: "\x1b[43m",
  bgBlue: "\x1b[44m",
  bgMagenta: "\x1b[45m",
  bgCyan: "\x1b[46m",
  bgWhite: "\x1b[47m",
}

export const emoji = {
  smile: "😊",
  laugh: "😂",
  thumbsUp: "👍",
  clap: "👏",
  heart: "❤️",
  star: "⭐",
  fire: "🔥",
  speaker: "🔊",
  watch: "👀",
  check: "✅",
  checkMark: "✔️",
  checkMarkBox: "☑️",
  cross: "❌",
  warning: "⚠️",
  info: "ℹ️",
  question: "❓",
}
